function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -5; // obj_mario
	global.__objectDepths[1] = -5; // obj_warpmario
	global.__objectDepths[2] = -5; // obj_jumpspawn
	global.__objectDepths[3] = -5; // obj_vinespawn
	global.__objectDepths[4] = 8; // obj_checkpoint
	global.__objectDepths[5] = 8; // obj_flagpole
	global.__objectDepths[6] = 8; // obj_flagpole_secret
	global.__objectDepths[7] = 8; // obj_incastle
	global.__objectDepths[8] = -7; // obj_levelmanager
	global.__objectDepths[9] = 0; // obj_stormmaker
	global.__objectDepths[10] = 0; // obj_bganimator
	global.__objectDepths[11] = 0; // obj_autoscroll
	global.__objectDepths[12] = -10; // obj_classicscroll
	global.__objectDepths[13] = 1; // obj_solid
	global.__objectDepths[14] = 1; // obj_solidtop
	global.__objectDepths[15] = 1; // obj_climb
	global.__objectDepths[16] = 1; // obj_climb_net
	global.__objectDepths[17] = 1; // obj_swim
	global.__objectDepths[18] = 1; // obj_slippery
	global.__objectDepths[19] = -1; // obj_hurtsolid
	global.__objectDepths[20] = -1; // obj_hurtsolid2
	global.__objectDepths[21] = 0; // obj_slope_r
	global.__objectDepths[22] = 0; // obj_slope_l
	global.__objectDepths[23] = 0; // obj_slope_sr
	global.__objectDepths[24] = 0; // obj_slope_sl
	global.__objectDepths[25] = 0; // obj_islope_r
	global.__objectDepths[26] = 0; // obj_islope_l
	global.__objectDepths[27] = 0; // obj_islope_sr
	global.__objectDepths[28] = 0; // obj_islope_sl
	global.__objectDepths[29] = 0; // obj_fillwater
	global.__objectDepths[30] = 0; // obj_stopblock
	global.__objectDepths[31] = 1; // obj_block
	global.__objectDepths[32] = 1; // obj_block_multicoin
	global.__objectDepths[33] = 1; // obj_block_multicoin_shroom
	global.__objectDepths[34] = 1; // obj_block_coinchain
	global.__objectDepths[35] = 0; // obj_block_hidden
	global.__objectDepths[36] = 1; // obj_block_triple
	global.__objectDepths[37] = 0; // obj_block_triple_hidden
	global.__objectDepths[38] = 1; // obj_block_spiked
	global.__objectDepths[39] = 1; // obj_block_winged
	global.__objectDepths[40] = 1; // obj_block_large
	global.__objectDepths[41] = 1; // obj_flowerblock
	global.__objectDepths[42] = 1; // obj_hammerblock
	global.__objectDepths[43] = 1; // obj_boomerangblock
	global.__objectDepths[44] = 1; // obj_leafblock
	global.__objectDepths[45] = 1; // obj_starblock
	global.__objectDepths[46] = 1; // obj_bombblock
	global.__objectDepths[47] = 1; // obj_shellblock
	global.__objectDepths[48] = 1; // obj_switchblock
	global.__objectDepths[49] = 1; // obj_kuriboblock
	global.__objectDepths[50] = 1; // obj_femaleblock
	global.__objectDepths[51] = 1; // obj_brick
	global.__objectDepths[52] = 1; // obj_bluebrick
	global.__objectDepths[53] = 1; // obj_redbrick
	global.__objectDepths[54] = 1; // obj_greenbrick
	global.__objectDepths[55] = 1; // obj_bombbrick
	global.__objectDepths[56] = 1; // obj_flipblock
	global.__objectDepths[57] = 1; // obj_noteblock
	global.__objectDepths[58] = 0; // obj_noteblock_hidden
	global.__objectDepths[59] = 1; // obj_noteblock_yellow
	global.__objectDepths[60] = 0; // obj_yellownoteblock_hidden
	global.__objectDepths[61] = 1; // obj_noteblock_warp
	global.__objectDepths[62] = 0; // obj_warpnoteblock_hidden
	global.__objectDepths[63] = 1; // obj_messageblock
	global.__objectDepths[64] = 1; // obj_block_pow
	global.__objectDepths[65] = 1; // obj_block_view
	global.__objectDepths[66] = 1; // obj_onoffblock
	global.__objectDepths[67] = 1; // obj_onoffplatform
	global.__objectDepths[68] = 1; // obj_area_red
	global.__objectDepths[69] = 1; // obj_area_blue
	global.__objectDepths[70] = 1; // obj_area_yellow
	global.__objectDepths[71] = 1; // obj_area_green
	global.__objectDepths[72] = 0; // obj_goomba
	global.__objectDepths[73] = 0; // obj_paragoomba
	global.__objectDepths[74] = 0; // obj_bubblegoomba
	global.__objectDepths[75] = 0; // obj_galoomba
	global.__objectDepths[76] = 0; // obj_galoomba_parachute
	global.__objectDepths[77] = 0; // obj_shoegoomba
	global.__objectDepths[78] = 0; // obj_koopa
	global.__objectDepths[79] = 0; // obj_koopa_red
	global.__objectDepths[80] = 0; // obj_koopa_hyper
	global.__objectDepths[81] = 0; // obj_parakoopa
	global.__objectDepths[82] = 0; // obj_parakoopa_red
	global.__objectDepths[83] = 0; // obj_parakoopa_hyper
	global.__objectDepths[84] = 0; // obj_jumpingkoopa
	global.__objectDepths[85] = 0; // obj_rex
	global.__objectDepths[86] = 0; // obj_spike
	global.__objectDepths[87] = 0; // obj_hoopster
	global.__objectDepths[88] = 0; // obj_ninji_red
	global.__objectDepths[89] = 0; // obj_wiggler
	global.__objectDepths[90] = 0; // obj_buzzybeetle
	global.__objectDepths[91] = 0; // obj_spiny
	global.__objectDepths[92] = 0; // obj_buzzy_ceiling
	global.__objectDepths[93] = 0; // obj_spiny_ceiling
	global.__objectDepths[94] = -1; // obj_piranhaplant
	global.__objectDepths[95] = -1; // obj_piranhaplant_down
	global.__objectDepths[96] = -1; // obj_piranhaplant_right
	global.__objectDepths[97] = -1; // obj_piranhaplant_left
	global.__objectDepths[98] = -1; // obj_piranhaplant_red
	global.__objectDepths[99] = -1; // obj_piranhaplant_down_red
	global.__objectDepths[100] = -1; // obj_piranhaplant_right_red
	global.__objectDepths[101] = -1; // obj_piranhaplant_left_red
	global.__objectDepths[102] = -1; // obj_piranhaplant_short
	global.__objectDepths[103] = -1; // obj_piranhaplant_down_short
	global.__objectDepths[104] = -1; // obj_jumppiranha
	global.__objectDepths[105] = -1; // obj_jumppiranha_red
	global.__objectDepths[106] = -1; // obj_firepiranha
	global.__objectDepths[107] = -1; // obj_firepiranha_down
	global.__objectDepths[108] = -1; // obj_firepiranha_right
	global.__objectDepths[109] = -1; // obj_firepiranha_left
	global.__objectDepths[110] = -1; // obj_firepiranha_red
	global.__objectDepths[111] = -1; // obj_firepiranha_down_red
	global.__objectDepths[112] = -1; // obj_firepiranha_right_red
	global.__objectDepths[113] = -1; // obj_firepiranha_left_red
	global.__objectDepths[114] = 0; // obj_ballpiranha
	global.__objectDepths[115] = 0; // obj_ptooie
	global.__objectDepths[116] = 0; // obj_swooper
	global.__objectDepths[117] = 0; // obj_busterbeetle
	global.__objectDepths[118] = 0; // obj_nokobon
	global.__objectDepths[119] = 0; // obj_spiketop
	global.__objectDepths[120] = 10; // obj_blargg
	global.__objectDepths[121] = 0; // obj_urchin
	global.__objectDepths[122] = 0; // obj_cheepcheep
	global.__objectDepths[123] = 0; // obj_spikedcheep
	global.__objectDepths[124] = -2; // obj_torpedolaunch
	global.__objectDepths[125] = 0; // obj_ripvanfish
	global.__objectDepths[126] = 0; // obj_porcupuffer
	global.__objectDepths[127] = 0; // obj_lavalotus
	global.__objectDepths[128] = 0; // obj_fishbone
	global.__objectDepths[129] = 0; // obj_blooper
	global.__objectDepths[130] = 0; // obj_nipper
	global.__objectDepths[131] = 0; // obj_montymole
	global.__objectDepths[132] = 0; // obj_lakitu
	global.__objectDepths[133] = 0; // obj_lakitu_ball
	global.__objectDepths[134] = 0; // obj_vulcanolotus
	global.__objectDepths[135] = 0; // obj_dinotorch
	global.__objectDepths[136] = 0; // obj_brickgoomba
	global.__objectDepths[137] = 0; // obj_firesnake
	global.__objectDepths[138] = 0; // obj_angrysun
	global.__objectDepths[139] = 0; // obj_pokey
	global.__objectDepths[140] = 0; // obj_boo
	global.__objectDepths[141] = 0; // obj_bigboo
	global.__objectDepths[142] = 0; // obj_stretchboo
	global.__objectDepths[143] = 0; // obj_blockboo
	global.__objectDepths[144] = 0; // obj_eerie
	global.__objectDepths[145] = 0; // obj_boocircle
	global.__objectDepths[146] = 0; // obj_boosnake
	global.__objectDepths[147] = 0; // obj_drybones
	global.__objectDepths[148] = 0; // obj_bonybeetle
	global.__objectDepths[149] = 10; // obj_podoboo
	global.__objectDepths[150] = 0; // obj_thwomp
	global.__objectDepths[151] = 0; // obj_thwimp
	global.__objectDepths[152] = 0; // obj_netkoopa
	global.__objectDepths[153] = 0; // obj_netkoopa_red
	global.__objectDepths[154] = 0; // obj_netkoopa_hyper
	global.__objectDepths[155] = 0; // obj_netspark
	global.__objectDepths[156] = 0; // obj_littlespark
	global.__objectDepths[157] = 0; // obj_fastspark
	global.__objectDepths[158] = 0; // obj_giantspark
	global.__objectDepths[159] = 0; // obj_phanto
	global.__objectDepths[160] = -1; // obj_rotodisc
	global.__objectDepths[161] = 0; // obj_firebar
	global.__objectDepths[162] = 0; // obj_firebar_large
	global.__objectDepths[163] = 0; // obj_grinder
	global.__objectDepths[164] = 0; // obj_linegrinder
	global.__objectDepths[165] = 0; // obj_ballnchain
	global.__objectDepths[166] = 0; // obj_magikoopa
	global.__objectDepths[167] = 0; // obj_podoboo_bounce
	global.__objectDepths[168] = 10; // obj_giantspike
	global.__objectDepths[169] = 10; // obj_crusher
	global.__objectDepths[170] = 0; // obj_bowserstatue
	global.__objectDepths[171] = 0; // obj_bowserstatue_gold
	global.__objectDepths[172] = 0; // obj_mechakoopa
	global.__objectDepths[173] = 0; // obj_bobomb
	global.__objectDepths[174] = 0; // obj_bobomb_parachute
	global.__objectDepths[175] = 0; // obj_bulletbill
	global.__objectDepths[176] = 0; // obj_bulletbill_side
	global.__objectDepths[177] = 0; // obj_bulletbill_homing
	global.__objectDepths[178] = 0; // obj_banzaibill
	global.__objectDepths[179] = 1; // obj_diacannon
	global.__objectDepths[180] = 1; // obj_bombcannon
	global.__objectDepths[181] = 1; // obj_sidecannon
	global.__objectDepths[182] = 1; // obj_quadcannon
	global.__objectDepths[183] = 0; // obj_largecannon
	global.__objectDepths[184] = 0; // obj_engine
	global.__objectDepths[185] = 0; // obj_engine2
	global.__objectDepths[186] = 0; // obj_vengine
	global.__objectDepths[187] = 0; // obj_vengine2
	global.__objectDepths[188] = 10; // obj_rockywrench
	global.__objectDepths[189] = 0; // obj_shyguy
	global.__objectDepths[190] = 0; // obj_shyguy_b
	global.__objectDepths[191] = 0; // obj_snifit
	global.__objectDepths[192] = 0; // obj_snifit_b
	global.__objectDepths[193] = 0; // obj_shyguybig
	global.__objectDepths[194] = 0; // obj_shyguybig_b
	global.__objectDepths[195] = 0; // obj_bombguy
	global.__objectDepths[196] = 0; // obj_ninji
	global.__objectDepths[197] = 0; // obj_tweeter
	global.__objectDepths[198] = 0; // obj_snifit_g
	global.__objectDepths[199] = 0; // obj_redhoopster
	global.__objectDepths[200] = 0; // obj_flurry
	global.__objectDepths[201] = 0; // obj_pokey_green
	global.__objectDepths[202] = 0; // obj_panser_red
	global.__objectDepths[203] = 0; // obj_panser_green
	global.__objectDepths[204] = 0; // obj_panser_blue
	global.__objectDepths[205] = 0; // obj_porcupo
	global.__objectDepths[206] = 9; // obj_bossdoor
	global.__objectDepths[207] = 0; // obj_endboss
	global.__objectDepths[208] = 0; // obj_boomboom
	global.__objectDepths[209] = 0; // obj_larry
	global.__objectDepths[210] = 0; // obj_morton
	global.__objectDepths[211] = 0; // obj_wendy
	global.__objectDepths[212] = 0; // obj_iggy
	global.__objectDepths[213] = 0; // obj_roy
	global.__objectDepths[214] = 0; // obj_lemmy
	global.__objectDepths[215] = 0; // obj_ludwig
	global.__objectDepths[216] = 0; // obj_birdo
	global.__objectDepths[217] = 0; // obj_mouser
	global.__objectDepths[218] = 9; // obj_reznor
	global.__objectDepths[219] = 0; // obj_classicbowser
	global.__objectDepths[220] = 9; // obj_bridge
	global.__objectDepths[221] = 1; // obj_axe
	global.__objectDepths[222] = 0; // obj_bowser
	global.__objectDepths[223] = 9; // obj_bowserbrick
	global.__objectDepths[224] = 0; // obj_hammerbro
	global.__objectDepths[225] = 0; // obj_firebro
	global.__objectDepths[226] = 0; // obj_boomerangbro
	global.__objectDepths[227] = 0; // obj_sledgebro
	global.__objectDepths[228] = 0; // obj_chainchomp
	global.__objectDepths[229] = 0; // obj_sumobro
	global.__objectDepths[230] = 0; // obj_chargingchuck
	global.__objectDepths[231] = 0; // obj_firechomp
	global.__objectDepths[232] = 9; // obj_flyingbro
	global.__objectDepths[233] = 0; // obj_pipeenemygenerator
	global.__objectDepths[234] = 0; // obj_bulletgenerator
	global.__objectDepths[235] = 0; // obj_stormgenerator
	global.__objectDepths[236] = 0; // obj_cheepgenerator
	global.__objectDepths[237] = -2; // obj_mapmario
	global.__objectDepths[238] = 0; // obj_lock
	global.__objectDepths[239] = 1; // obj_levelpanel
	global.__objectDepths[240] = 1; // obj_levelcastle
	global.__objectDepths[241] = 1; // obj_mushhouse
	global.__objectDepths[242] = 0; // obj_start
	global.__objectDepths[243] = 2; // obj_mapcoin
	global.__objectDepths[244] = 2; // obj_maphills
	global.__objectDepths[245] = 1; // obj_roulettelevel
	global.__objectDepths[246] = 0; // obj_mapbro
	global.__objectDepths[247] = 1; // obj_mappipe
	global.__objectDepths[248] = 1; // obj_palace_red
	global.__objectDepths[249] = 1; // obj_palace_blue
	global.__objectDepths[250] = 1; // obj_palace_yellow
	global.__objectDepths[251] = 1; // obj_palace_green
	global.__objectDepths[252] = -2; // obj_saver
	global.__objectDepths[253] = 9; // obj_watertop
	global.__objectDepths[254] = 9; // obj_wfalltop
	global.__objectDepths[255] = 9; // obj_wfall
	global.__objectDepths[256] = 9; // obj_vine
	global.__objectDepths[257] = 1; // obj_muncher
	global.__objectDepths[258] = 1; // obj_jelectro
	global.__objectDepths[259] = 1; // obj_lava
	global.__objectDepths[260] = 1; // obj_lava_r
	global.__objectDepths[261] = 1; // obj_lava_l
	global.__objectDepths[262] = 1; // obj_lava_sr
	global.__objectDepths[263] = 1; // obj_lava_sl
	global.__objectDepths[264] = 1; // obj_platform_moving
	global.__objectDepths[265] = 1; // obj_platform_touch
	global.__objectDepths[266] = 1; // obj_platform_falling
	global.__objectDepths[267] = 1; // obj_donut
	global.__objectDepths[268] = 1; // obj_donut_red
	global.__objectDepths[269] = 1; // obj_platformspin
	global.__objectDepths[270] = 1; // obj_platformtimed
	global.__objectDepths[271] = 1; // obj_arrowplatform
	global.__objectDepths[272] = 9; // obj_movingpipe
	global.__objectDepths[273] = 1; // obj_parabeetle
	global.__objectDepths[274] = 0; // obj_blocktrain
	global.__objectDepths[275] = 0; // obj_bouncer
	global.__objectDepths[276] = 2; // obj_expandplatform_hv
	global.__objectDepths[277] = 2; // obj_expandplatform_h
	global.__objectDepths[278] = 2; // obj_expandplatform_v
	global.__objectDepths[279] = 0; // obj_conveyor_left
	global.__objectDepths[280] = 0; // obj_conveyor_right
	global.__objectDepths[281] = 0; // obj_movingrope
	global.__objectDepths[282] = 0; // obj_movingrope_touch
	global.__objectDepths[283] = 0; // obj_movingsaw
	global.__objectDepths[284] = 10; // obj_skullraft
	global.__objectDepths[285] = 1; // obj_coin
	global.__objectDepths[286] = 1; // obj_pcoin
	global.__objectDepths[287] = 0; // obj_bubble_coin
	global.__objectDepths[288] = 0; // obj_bubble_item
	global.__objectDepths[289] = 1; // obj_icecoin
	global.__objectDepths[290] = 1; // obj_icemuncher
	global.__objectDepths[291] = 0; // obj_spring
	global.__objectDepths[292] = 0; // obj_spring_hidden
	global.__objectDepths[293] = 0; // obj_spring_timed
	global.__objectDepths[294] = 0; // obj_spring_super
	global.__objectDepths[295] = 0; // obj_propellerblock
	global.__objectDepths[296] = 2; // obj_3upmoon
	global.__objectDepths[297] = 1; // obj_acecoin
	global.__objectDepths[298] = 0; // obj_pswitch
	global.__objectDepths[299] = 0; // obj_eswitch
	global.__objectDepths[300] = 1; // obj_eswitch_red
	global.__objectDepths[301] = 1; // obj_pplatform
	global.__objectDepths[302] = -6; // obj_quicksand
	global.__objectDepths[303] = 0; // obj_blowpipe_top
	global.__objectDepths[304] = 0; // obj_blowpipe_bottom
	global.__objectDepths[305] = 0; // obj_blowpipe_left
	global.__objectDepths[306] = 0; // obj_blowpipe_right
	global.__objectDepths[307] = 0; // obj_walltriangle_r
	global.__objectDepths[308] = 0; // obj_walltriangle_ir
	global.__objectDepths[309] = 0; // obj_walltriangle_l
	global.__objectDepths[310] = 0; // obj_walltriangle_il
	global.__objectDepths[311] = 1; // obj_flippers_top
	global.__objectDepths[312] = 1; // obj_flippers_bottom
	global.__objectDepths[313] = 1; // obj_flippers_left
	global.__objectDepths[314] = 1; // obj_flippers_right
	global.__objectDepths[315] = 0; // obj_fallingspike
	global.__objectDepths[316] = 8; // obj_veggie_small
	global.__objectDepths[317] = 8; // obj_veggie_large
	global.__objectDepths[318] = 8; // obj_veggie_coin
	global.__objectDepths[319] = 8; // obj_veggie_multicoin
	global.__objectDepths[320] = 8; // obj_veggie_sprout
	global.__objectDepths[321] = 8; // obj_veggie_bomb
	global.__objectDepths[322] = 8; // obj_veggie_shell
	global.__objectDepths[323] = 1; // obj_powblock
	global.__objectDepths[324] = 1; // obj_mblock
	global.__objectDepths[325] = 1; // obj_pullmush
	global.__objectDepths[326] = 8; // obj_digsand
	global.__objectDepths[327] = 0; // obj_key
	global.__objectDepths[328] = 1; // obj_keyhole
	global.__objectDepths[329] = -2; // obj_warptop
	global.__objectDepths[330] = -2; // obj_warpbottom
	global.__objectDepths[331] = -2; // obj_warpleft
	global.__objectDepths[332] = -2; // obj_warpright
	global.__objectDepths[333] = 2; // obj_door
	global.__objectDepths[334] = 2; // obj_door_locked
	global.__objectDepths[335] = 2; // obj_door_hidden
	global.__objectDepths[336] = 2; // obj_door_hidden_locked
	global.__objectDepths[337] = 2; // obj_door_bomb
	global.__objectDepths[338] = -2; // obj_postchange
	global.__objectDepths[339] = -2; // obj_warproom
	global.__objectDepths[340] = -2; // obj_warpcannon
	global.__objectDepths[341] = -2; // obj_giantwarpcannon
	global.__objectDepths[342] = 0; // obj_physicsparent
	global.__objectDepths[343] = 0; // obj_powerupparent
	global.__objectDepths[344] = 0; // obj_enemyparent
	global.__objectDepths[345] = 0; // obj_deactenemyparent
	global.__objectDepths[346] = 0; // obj_subconenemyparent
	global.__objectDepths[347] = 0; // obj_bossparent
	global.__objectDepths[348] = 1; // obj_blockparent
	global.__objectDepths[349] = 0; // obj_grayblockparent
	global.__objectDepths[350] = 0; // obj_worldparent
	global.__objectDepths[351] = 0; // obj_panelparent
	global.__objectDepths[352] = 0; // obj_pullparent
	global.__objectDepths[353] = 0; // obj_carryparent
	global.__objectDepths[354] = 0; // obj_holdparent
	global.__objectDepths[355] = 0; // obj_slopeparent
	global.__objectDepths[356] = 0; // obj_deactivation
	global.__objectDepths[357] = -5; // obj_deadmario
	global.__objectDepths[358] = -5; // obj_goalmario
	global.__objectDepths[359] = -5; // obj_warpnoteblock
	global.__objectDepths[360] = -5; // obj_doormario
	global.__objectDepths[361] = -5; // obj_puller
	global.__objectDepths[362] = -5; // obj_wallrunner
	global.__objectDepths[363] = 0; // obj_slider
	global.__objectDepths[364] = -5; // obj_spinner
	global.__objectDepths[365] = 1; // obj_statue
	global.__objectDepths[366] = -5; // obj_rockroller
	global.__objectDepths[367] = -5; // obj_karateattack
	global.__objectDepths[368] = 2; // obj_1up
	global.__objectDepths[369] = 2; // obj_poison
	global.__objectDepths[370] = 2; // obj_mushroom
	global.__objectDepths[371] = 2; // obj_fireflower
	global.__objectDepths[372] = 2; // obj_hammersuit
	global.__objectDepths[373] = 2; // obj_leaf
	global.__objectDepths[374] = 2; // obj_tanookisuit
	global.__objectDepths[375] = 2; // obj_frogsuit
	global.__objectDepths[376] = 2; // obj_bombshroom
	global.__objectDepths[377] = 2; // obj_iceflower
	global.__objectDepths[378] = 2; // obj_superflower
	global.__objectDepths[379] = 2; // obj_carrot
	global.__objectDepths[380] = 2; // obj_ninjasuit
	global.__objectDepths[381] = 2; // obj_beeshroom
	global.__objectDepths[382] = 2; // obj_blueshell
	global.__objectDepths[383] = 2; // obj_penguinsuit
	global.__objectDepths[384] = 2; // obj_propellershroom
	global.__objectDepths[385] = 2; // obj_boomerangflower
	global.__objectDepths[386] = 2; // obj_walljumpshroom
	global.__objectDepths[387] = 2; // obj_acorn
	global.__objectDepths[388] = 2; // obj_cloudflower
	global.__objectDepths[389] = 2; // obj_rockshroom
	global.__objectDepths[390] = 2; // obj_pyreflower
	global.__objectDepths[391] = 2; // obj_swoopersuit
	global.__objectDepths[392] = 2; // obj_karatesuit
	global.__objectDepths[393] = 2; // obj_supercrown
	global.__objectDepths[394] = 2; // obj_star
	global.__objectDepths[395] = 2; // obj_hatch
	global.__objectDepths[396] = -5; // obj_yoshi
	global.__objectDepths[397] = -4; // obj_yoshi_runaway
	global.__objectDepths[398] = -4; // obj_yoshi_abandon
	global.__objectDepths[399] = -6; // obj_tongue
	global.__objectDepths[400] = -2; // obj_yoshifire
	global.__objectDepths[401] = -5; // obj_kuriboshoe
	global.__objectDepths[402] = 0; // obj_getshoe
	global.__objectDepths[403] = 2; // obj_powerupsprout
	global.__objectDepths[404] = -8; // obj_reserveitem
	global.__objectDepths[405] = 0; // obj_grasspowerup
	global.__objectDepths[406] = 0; // obj_getpowerup
	global.__objectDepths[407] = -2; // obj_fireball
	global.__objectDepths[408] = -2; // obj_hammer
	global.__objectDepths[409] = -2; // obj_minibomb
	global.__objectDepths[410] = -2; // obj_iceball
	global.__objectDepths[411] = -2; // obj_superball
	global.__objectDepths[412] = -2; // obj_shuriken
	global.__objectDepths[413] = -2; // obj_boomerang_b
	global.__objectDepths[414] = 1; // obj_cloud
	global.__objectDepths[415] = -2; // obj_pyreball
	global.__objectDepths[416] = -6; // obj_invincibility
	global.__objectDepths[417] = 0; // obj_galoomba_hold
	global.__objectDepths[418] = 0; // obj_spikeball
	global.__objectDepths[419] = 0; // obj_wiggler_body
	global.__objectDepths[420] = 11; // obj_plantfire
	global.__objectDepths[421] = 0; // obj_plantball
	global.__objectDepths[422] = 0; // obj_busterpickup
	global.__objectDepths[423] = 10; // obj_blargg_jump
	global.__objectDepths[424] = -1; // obj_torpedoglove
	global.__objectDepths[425] = 0; // obj_torpedoted
	global.__objectDepths[426] = 0; // obj_lavalotusball
	global.__objectDepths[427] = 0; // obj_monty
	global.__objectDepths[428] = 0; // obj_montyjump
	global.__objectDepths[429] = 0; // obj_lakitu_egg
	global.__objectDepths[430] = 0; // obj_lakituticker
	global.__objectDepths[431] = 0; // obj_lotusball
	global.__objectDepths[432] = 0; // obj_dinoflames
	global.__objectDepths[433] = 1; // obj_firesnake_part
	global.__objectDepths[434] = 0; // obj_angrysun_movement
	global.__objectDepths[435] = 0; // obj_boocircle_boo
	global.__objectDepths[436] = 1; // obj_boosnake_trail
	global.__objectDepths[437] = 0; // obj_crumblebones
	global.__objectDepths[438] = 0; // obj_rotodisc_path
	global.__objectDepths[439] = 0; // obj_firebarball
	global.__objectDepths[440] = 0; // obj_chains
	global.__objectDepths[441] = 0; // obj_magikoopa2
	global.__objectDepths[442] = 0; // obj_magic
	global.__objectDepths[443] = 1; // obj_bowserstatue_fire
	global.__objectDepths[444] = 0; // obj_mechakoopa_hold
	global.__objectDepths[445] = 0; // obj_bobomb_hold
	global.__objectDepths[446] = 0; // obj_cannonbomb
	global.__objectDepths[447] = 10; // obj_bullet
	global.__objectDepths[448] = 10; // obj_bullet_side
	global.__objectDepths[449] = 10; // obj_bullet_homing
	global.__objectDepths[450] = 0; // obj_cannonball
	global.__objectDepths[451] = 0; // obj_largeball
	global.__objectDepths[452] = 0; // obj_engines
	global.__objectDepths[453] = 0; // obj_engines2
	global.__objectDepths[454] = 0; // obj_vengines
	global.__objectDepths[455] = 0; // obj_vengines2
	global.__objectDepths[456] = 0; // obj_wrench
	global.__objectDepths[457] = -1; // obj_snifitball
	global.__objectDepths[458] = -6; // obj_bombguyup
	global.__objectDepths[459] = 0; // obj_panserfire
	global.__objectDepths[460] = 0; // obj_magiccircle
	global.__objectDepths[461] = 0; // obj_magicring
	global.__objectDepths[462] = 0; // obj_magicball
	global.__objectDepths[463] = 0; // obj_lemmyball
	global.__objectDepths[464] = 1; // obj_birdo_egg
	global.__objectDepths[465] = 0; // obj_mouser_bomb
	global.__objectDepths[466] = -1; // obj_mouser_thrownbomb
	global.__objectDepths[467] = 1; // obj_reznor_platform
	global.__objectDepths[468] = 1; // obj_reznor_enemy
	global.__objectDepths[469] = 0; // obj_reznor_fire
	global.__objectDepths[470] = 1; // obj_bowserfire
	global.__objectDepths[471] = -2; // obj_enemy_dead
	global.__objectDepths[472] = -2; // obj_enemy_multidead
	global.__objectDepths[473] = -2; // obj_enemy_stomped
	global.__objectDepths[474] = -4; // obj_enemy_frozen
	global.__objectDepths[475] = -6; // obj_frozenenemy_pickup
	global.__objectDepths[476] = -6; // obj_vegenemy
	global.__objectDepths[477] = 0; // obj_stomped
	global.__objectDepths[478] = 0; // obj_shell
	global.__objectDepths[479] = -4; // obj_shell_held
	global.__objectDepths[480] = -2; // obj_brohammer
	global.__objectDepths[481] = 0; // obj_brofire
	global.__objectDepths[482] = -2; // obj_boomerang
	global.__objectDepths[483] = 0; // obj_lightning
	global.__objectDepths[484] = 0; // obj_sumoflame
	global.__objectDepths[485] = 1; // obj_firechomp_tail
	global.__objectDepths[486] = 0; // obj_flyingbro_rider
	global.__objectDepths[487] = 0; // obj_generatorcheep
	global.__objectDepths[488] = 2; // obj_blockcoin
	global.__objectDepths[489] = 2; // obj_beanstalk
	global.__objectDepths[490] = 0; // obj_vinewarp
	global.__objectDepths[491] = 2; // obj_coinchain
	global.__objectDepths[492] = 0; // obj_thrownbrick
	global.__objectDepths[493] = 0; // obj_shard
	global.__objectDepths[494] = 0; // obj_arrowplatform_move
	global.__objectDepths[495] = 0; // obj_blocktrain_front
	global.__objectDepths[496] = 1; // obj_blocktrain_middle
	global.__objectDepths[497] = 0; // obj_blocktrain_back
	global.__objectDepths[498] = 0; // obj_blocktrain_killer
	global.__objectDepths[499] = 1; // obj_expandplatblock
	global.__objectDepths[500] = 0; // obj_movingrope_rope
	global.__objectDepths[501] = -6; // obj_vegetable_small
	global.__objectDepths[502] = -6; // obj_vegetable_large
	global.__objectDepths[503] = -1; // obj_veggiecoin
	global.__objectDepths[504] = -1; // obj_multiveggiecoin
	global.__objectDepths[505] = -6; // obj_grassbomb
	global.__objectDepths[506] = -6; // obj_smb2shellup
	global.__objectDepths[507] = -6; // obj_pow
	global.__objectDepths[508] = 0; // obj_powkiller
	global.__objectDepths[509] = -6; // obj_mblockup
	global.__objectDepths[510] = 0; // obj_coinchange
	global.__objectDepths[511] = 0; // obj_spring_blue
	global.__objectDepths[512] = 0; // obj_blownbubble
	global.__objectDepths[513] = -2; // obj_score
	global.__objectDepths[514] = -1; // obj_smoke
	global.__objectDepths[515] = -6; // obj_statuesmoke
	global.__objectDepths[516] = -1; // obj_spinsmoke
	global.__objectDepths[517] = -6; // obj_spinthump
	global.__objectDepths[518] = -1; // obj_bubble
	global.__objectDepths[519] = -1; // obj_sparkletrail
	global.__objectDepths[520] = -6; // obj_rain
	global.__objectDepths[521] = -1; // obj_mapcard
	global.__objectDepths[522] = -1; // obj_explosion
	global.__objectDepths[523] = 8; // obj_flag
	global.__objectDepths[524] = 20; // obj_lightningsheet
	global.__objectDepths[525] = -9; // obj_messagebox
	global.__objectDepths[526] = -9; // obj_pausemenu
	global.__objectDepths[527] = -9; // obj_savemenu
	global.__objectDepths[528] = -8; // obj_inventoryprev
	global.__objectDepths[529] = 0; // obj_blockbumper
	global.__objectDepths[530] = 0; // obj_stomp
	global.__objectDepths[531] = -99; // obj_persistent
	global.__objectDepths[532] = 0; // obj_titlescreen
	global.__objectDepths[533] = 0; // obj_mushtoad
	global.__objectDepths[534] = 8; // obj_chest
	global.__objectDepths[535] = 0; // obj_gameover
	global.__objectDepths[536] = -100; // obj_mariostart
	global.__objectDepths[537] = 0; // obj_roulettemanager
	global.__objectDepths[538] = -1; // obj_cardmanager
	global.__objectDepths[539] = 0; // obj_card
	global.__objectDepths[540] = 0; // obj_switch
	global.__objectDepths[541] = 8; // obj_hammerprize
	global.__objectDepths[542] = -5; // obj_mappipemanager
	global.__objectDepths[543] = 0; // obj_warpmapscreen
	global.__objectDepths[544] = -1; // obj_up
	global.__objectDepths[545] = -1; // obj_down
	global.__objectDepths[546] = -1; // obj_left
	global.__objectDepths[547] = -1; // obj_right
	global.__objectDepths[548] = -1; // obj_endmarker
	global.__objectDepths[549] = -1; // obj_speedmarker
	global.__objectDepths[550] = -1; // obj_clockwise
	global.__objectDepths[551] = -1; // obj_cclockwise
	global.__objectDepths[552] = -1; // obj_clockwiseb
	global.__objectDepths[553] = -1; // obj_cclockwiseb


	global.__objectNames[0] = "obj_mario";
	global.__objectNames[1] = "obj_warpmario";
	global.__objectNames[2] = "obj_jumpspawn";
	global.__objectNames[3] = "obj_vinespawn";
	global.__objectNames[4] = "obj_checkpoint";
	global.__objectNames[5] = "obj_flagpole";
	global.__objectNames[6] = "obj_flagpole_secret";
	global.__objectNames[7] = "obj_incastle";
	global.__objectNames[8] = "obj_levelmanager";
	global.__objectNames[9] = "obj_stormmaker";
	global.__objectNames[10] = "obj_bganimator";
	global.__objectNames[11] = "obj_autoscroll";
	global.__objectNames[12] = "obj_classicscroll";
	global.__objectNames[13] = "obj_solid";
	global.__objectNames[14] = "obj_solidtop";
	global.__objectNames[15] = "obj_climb";
	global.__objectNames[16] = "obj_climb_net";
	global.__objectNames[17] = "obj_swim";
	global.__objectNames[18] = "obj_slippery";
	global.__objectNames[19] = "obj_hurtsolid";
	global.__objectNames[20] = "obj_hurtsolid2";
	global.__objectNames[21] = "obj_slope_r";
	global.__objectNames[22] = "obj_slope_l";
	global.__objectNames[23] = "obj_slope_sr";
	global.__objectNames[24] = "obj_slope_sl";
	global.__objectNames[25] = "obj_islope_r";
	global.__objectNames[26] = "obj_islope_l";
	global.__objectNames[27] = "obj_islope_sr";
	global.__objectNames[28] = "obj_islope_sl";
	global.__objectNames[29] = "obj_fillwater";
	global.__objectNames[30] = "obj_stopblock";
	global.__objectNames[31] = "obj_block";
	global.__objectNames[32] = "obj_block_multicoin";
	global.__objectNames[33] = "obj_block_multicoin_shroom";
	global.__objectNames[34] = "obj_block_coinchain";
	global.__objectNames[35] = "obj_block_hidden";
	global.__objectNames[36] = "obj_block_triple";
	global.__objectNames[37] = "obj_block_triple_hidden";
	global.__objectNames[38] = "obj_block_spiked";
	global.__objectNames[39] = "obj_block_winged";
	global.__objectNames[40] = "obj_block_large";
	global.__objectNames[41] = "obj_flowerblock";
	global.__objectNames[42] = "obj_hammerblock";
	global.__objectNames[43] = "obj_boomerangblock";
	global.__objectNames[44] = "obj_leafblock";
	global.__objectNames[45] = "obj_starblock";
	global.__objectNames[46] = "obj_bombblock";
	global.__objectNames[47] = "obj_shellblock";
	global.__objectNames[48] = "obj_switchblock";
	global.__objectNames[49] = "obj_kuriboblock";
	global.__objectNames[50] = "obj_femaleblock";
	global.__objectNames[51] = "obj_brick";
	global.__objectNames[52] = "obj_bluebrick";
	global.__objectNames[53] = "obj_redbrick";
	global.__objectNames[54] = "obj_greenbrick";
	global.__objectNames[55] = "obj_bombbrick";
	global.__objectNames[56] = "obj_flipblock";
	global.__objectNames[57] = "obj_noteblock";
	global.__objectNames[58] = "obj_noteblock_hidden";
	global.__objectNames[59] = "obj_noteblock_yellow";
	global.__objectNames[60] = "obj_yellownoteblock_hidden";
	global.__objectNames[61] = "obj_noteblock_warp";
	global.__objectNames[62] = "obj_warpnoteblock_hidden";
	global.__objectNames[63] = "obj_messageblock";
	global.__objectNames[64] = "obj_block_pow";
	global.__objectNames[65] = "obj_block_view";
	global.__objectNames[66] = "obj_onoffblock";
	global.__objectNames[67] = "obj_onoffplatform";
	global.__objectNames[68] = "obj_area_red";
	global.__objectNames[69] = "obj_area_blue";
	global.__objectNames[70] = "obj_area_yellow";
	global.__objectNames[71] = "obj_area_green";
	global.__objectNames[72] = "obj_goomba";
	global.__objectNames[73] = "obj_paragoomba";
	global.__objectNames[74] = "obj_bubblegoomba";
	global.__objectNames[75] = "obj_galoomba";
	global.__objectNames[76] = "obj_galoomba_parachute";
	global.__objectNames[77] = "obj_shoegoomba";
	global.__objectNames[78] = "obj_koopa";
	global.__objectNames[79] = "obj_koopa_red";
	global.__objectNames[80] = "obj_koopa_hyper";
	global.__objectNames[81] = "obj_parakoopa";
	global.__objectNames[82] = "obj_parakoopa_red";
	global.__objectNames[83] = "obj_parakoopa_hyper";
	global.__objectNames[84] = "obj_jumpingkoopa";
	global.__objectNames[85] = "obj_rex";
	global.__objectNames[86] = "obj_spike";
	global.__objectNames[87] = "obj_hoopster";
	global.__objectNames[88] = "obj_ninji_red";
	global.__objectNames[89] = "obj_wiggler";
	global.__objectNames[90] = "obj_buzzybeetle";
	global.__objectNames[91] = "obj_spiny";
	global.__objectNames[92] = "obj_buzzy_ceiling";
	global.__objectNames[93] = "obj_spiny_ceiling";
	global.__objectNames[94] = "obj_piranhaplant";
	global.__objectNames[95] = "obj_piranhaplant_down";
	global.__objectNames[96] = "obj_piranhaplant_right";
	global.__objectNames[97] = "obj_piranhaplant_left";
	global.__objectNames[98] = "obj_piranhaplant_red";
	global.__objectNames[99] = "obj_piranhaplant_down_red";
	global.__objectNames[100] = "obj_piranhaplant_right_red";
	global.__objectNames[101] = "obj_piranhaplant_left_red";
	global.__objectNames[102] = "obj_piranhaplant_short";
	global.__objectNames[103] = "obj_piranhaplant_down_short";
	global.__objectNames[104] = "obj_jumppiranha";
	global.__objectNames[105] = "obj_jumppiranha_red";
	global.__objectNames[106] = "obj_firepiranha";
	global.__objectNames[107] = "obj_firepiranha_down";
	global.__objectNames[108] = "obj_firepiranha_right";
	global.__objectNames[109] = "obj_firepiranha_left";
	global.__objectNames[110] = "obj_firepiranha_red";
	global.__objectNames[111] = "obj_firepiranha_down_red";
	global.__objectNames[112] = "obj_firepiranha_right_red";
	global.__objectNames[113] = "obj_firepiranha_left_red";
	global.__objectNames[114] = "obj_ballpiranha";
	global.__objectNames[115] = "obj_ptooie";
	global.__objectNames[116] = "obj_swooper";
	global.__objectNames[117] = "obj_busterbeetle";
	global.__objectNames[118] = "obj_nokobon";
	global.__objectNames[119] = "obj_spiketop";
	global.__objectNames[120] = "obj_blargg";
	global.__objectNames[121] = "obj_urchin";
	global.__objectNames[122] = "obj_cheepcheep";
	global.__objectNames[123] = "obj_spikedcheep";
	global.__objectNames[124] = "obj_torpedolaunch";
	global.__objectNames[125] = "obj_ripvanfish";
	global.__objectNames[126] = "obj_porcupuffer";
	global.__objectNames[127] = "obj_lavalotus";
	global.__objectNames[128] = "obj_fishbone";
	global.__objectNames[129] = "obj_blooper";
	global.__objectNames[130] = "obj_nipper";
	global.__objectNames[131] = "obj_montymole";
	global.__objectNames[132] = "obj_lakitu";
	global.__objectNames[133] = "obj_lakitu_ball";
	global.__objectNames[134] = "obj_vulcanolotus";
	global.__objectNames[135] = "obj_dinotorch";
	global.__objectNames[136] = "obj_brickgoomba";
	global.__objectNames[137] = "obj_firesnake";
	global.__objectNames[138] = "obj_angrysun";
	global.__objectNames[139] = "obj_pokey";
	global.__objectNames[140] = "obj_boo";
	global.__objectNames[141] = "obj_bigboo";
	global.__objectNames[142] = "obj_stretchboo";
	global.__objectNames[143] = "obj_blockboo";
	global.__objectNames[144] = "obj_eerie";
	global.__objectNames[145] = "obj_boocircle";
	global.__objectNames[146] = "obj_boosnake";
	global.__objectNames[147] = "obj_drybones";
	global.__objectNames[148] = "obj_bonybeetle";
	global.__objectNames[149] = "obj_podoboo";
	global.__objectNames[150] = "obj_thwomp";
	global.__objectNames[151] = "obj_thwimp";
	global.__objectNames[152] = "obj_netkoopa";
	global.__objectNames[153] = "obj_netkoopa_red";
	global.__objectNames[154] = "obj_netkoopa_hyper";
	global.__objectNames[155] = "obj_netspark";
	global.__objectNames[156] = "obj_littlespark";
	global.__objectNames[157] = "obj_fastspark";
	global.__objectNames[158] = "obj_giantspark";
	global.__objectNames[159] = "obj_phanto";
	global.__objectNames[160] = "obj_rotodisc";
	global.__objectNames[161] = "obj_firebar";
	global.__objectNames[162] = "obj_firebar_large";
	global.__objectNames[163] = "obj_grinder";
	global.__objectNames[164] = "obj_linegrinder";
	global.__objectNames[165] = "obj_ballnchain";
	global.__objectNames[166] = "obj_magikoopa";
	global.__objectNames[167] = "obj_podoboo_bounce";
	global.__objectNames[168] = "obj_giantspike";
	global.__objectNames[169] = "obj_crusher";
	global.__objectNames[170] = "obj_bowserstatue";
	global.__objectNames[171] = "obj_bowserstatue_gold";
	global.__objectNames[172] = "obj_mechakoopa";
	global.__objectNames[173] = "obj_bobomb";
	global.__objectNames[174] = "obj_bobomb_parachute";
	global.__objectNames[175] = "obj_bulletbill";
	global.__objectNames[176] = "obj_bulletbill_side";
	global.__objectNames[177] = "obj_bulletbill_homing";
	global.__objectNames[178] = "obj_banzaibill";
	global.__objectNames[179] = "obj_diacannon";
	global.__objectNames[180] = "obj_bombcannon";
	global.__objectNames[181] = "obj_sidecannon";
	global.__objectNames[182] = "obj_quadcannon";
	global.__objectNames[183] = "obj_largecannon";
	global.__objectNames[184] = "obj_engine";
	global.__objectNames[185] = "obj_engine2";
	global.__objectNames[186] = "obj_vengine";
	global.__objectNames[187] = "obj_vengine2";
	global.__objectNames[188] = "obj_rockywrench";
	global.__objectNames[189] = "obj_shyguy";
	global.__objectNames[190] = "obj_shyguy_b";
	global.__objectNames[191] = "obj_snifit";
	global.__objectNames[192] = "obj_snifit_b";
	global.__objectNames[193] = "obj_shyguybig";
	global.__objectNames[194] = "obj_shyguybig_b";
	global.__objectNames[195] = "obj_bombguy";
	global.__objectNames[196] = "obj_ninji";
	global.__objectNames[197] = "obj_tweeter";
	global.__objectNames[198] = "obj_snifit_g";
	global.__objectNames[199] = "obj_redhoopster";
	global.__objectNames[200] = "obj_flurry";
	global.__objectNames[201] = "obj_pokey_green";
	global.__objectNames[202] = "obj_panser_red";
	global.__objectNames[203] = "obj_panser_green";
	global.__objectNames[204] = "obj_panser_blue";
	global.__objectNames[205] = "obj_porcupo";
	global.__objectNames[206] = "obj_bossdoor";
	global.__objectNames[207] = "obj_endboss";
	global.__objectNames[208] = "obj_boomboom";
	global.__objectNames[209] = "obj_larry";
	global.__objectNames[210] = "obj_morton";
	global.__objectNames[211] = "obj_wendy";
	global.__objectNames[212] = "obj_iggy";
	global.__objectNames[213] = "obj_roy";
	global.__objectNames[214] = "obj_lemmy";
	global.__objectNames[215] = "obj_ludwig";
	global.__objectNames[216] = "obj_birdo";
	global.__objectNames[217] = "obj_mouser";
	global.__objectNames[218] = "obj_reznor";
	global.__objectNames[219] = "obj_classicbowser";
	global.__objectNames[220] = "obj_bridge";
	global.__objectNames[221] = "obj_axe";
	global.__objectNames[222] = "obj_bowser";
	global.__objectNames[223] = "obj_bowserbrick";
	global.__objectNames[224] = "obj_hammerbro";
	global.__objectNames[225] = "obj_firebro";
	global.__objectNames[226] = "obj_boomerangbro";
	global.__objectNames[227] = "obj_sledgebro";
	global.__objectNames[228] = "obj_chainchomp";
	global.__objectNames[229] = "obj_sumobro";
	global.__objectNames[230] = "obj_chargingchuck";
	global.__objectNames[231] = "obj_firechomp";
	global.__objectNames[232] = "obj_flyingbro";
	global.__objectNames[233] = "obj_pipeenemygenerator";
	global.__objectNames[234] = "obj_bulletgenerator";
	global.__objectNames[235] = "obj_stormgenerator";
	global.__objectNames[236] = "obj_cheepgenerator";
	global.__objectNames[237] = "obj_mapmario";
	global.__objectNames[238] = "obj_lock";
	global.__objectNames[239] = "obj_levelpanel";
	global.__objectNames[240] = "obj_levelcastle";
	global.__objectNames[241] = "obj_mushhouse";
	global.__objectNames[242] = "obj_start";
	global.__objectNames[243] = "obj_mapcoin";
	global.__objectNames[244] = "obj_maphills";
	global.__objectNames[245] = "obj_roulettelevel";
	global.__objectNames[246] = "obj_mapbro";
	global.__objectNames[247] = "obj_mappipe";
	global.__objectNames[248] = "obj_palace_red";
	global.__objectNames[249] = "obj_palace_blue";
	global.__objectNames[250] = "obj_palace_yellow";
	global.__objectNames[251] = "obj_palace_green";
	global.__objectNames[252] = "obj_saver";
	global.__objectNames[253] = "obj_watertop";
	global.__objectNames[254] = "obj_wfalltop";
	global.__objectNames[255] = "obj_wfall";
	global.__objectNames[256] = "obj_vine";
	global.__objectNames[257] = "obj_muncher";
	global.__objectNames[258] = "obj_jelectro";
	global.__objectNames[259] = "obj_lava";
	global.__objectNames[260] = "obj_lava_r";
	global.__objectNames[261] = "obj_lava_l";
	global.__objectNames[262] = "obj_lava_sr";
	global.__objectNames[263] = "obj_lava_sl";
	global.__objectNames[264] = "obj_platform_moving";
	global.__objectNames[265] = "obj_platform_touch";
	global.__objectNames[266] = "obj_platform_falling";
	global.__objectNames[267] = "obj_donut";
	global.__objectNames[268] = "obj_donut_red";
	global.__objectNames[269] = "obj_platformspin";
	global.__objectNames[270] = "obj_platformtimed";
	global.__objectNames[271] = "obj_arrowplatform";
	global.__objectNames[272] = "obj_movingpipe";
	global.__objectNames[273] = "obj_parabeetle";
	global.__objectNames[274] = "obj_blocktrain";
	global.__objectNames[275] = "obj_bouncer";
	global.__objectNames[276] = "obj_expandplatform_hv";
	global.__objectNames[277] = "obj_expandplatform_h";
	global.__objectNames[278] = "obj_expandplatform_v";
	global.__objectNames[279] = "obj_conveyor_left";
	global.__objectNames[280] = "obj_conveyor_right";
	global.__objectNames[281] = "obj_movingrope";
	global.__objectNames[282] = "obj_movingrope_touch";
	global.__objectNames[283] = "obj_movingsaw";
	global.__objectNames[284] = "obj_skullraft";
	global.__objectNames[285] = "obj_coin";
	global.__objectNames[286] = "obj_pcoin";
	global.__objectNames[287] = "obj_bubble_coin";
	global.__objectNames[288] = "obj_bubble_item";
	global.__objectNames[289] = "obj_icecoin";
	global.__objectNames[290] = "obj_icemuncher";
	global.__objectNames[291] = "obj_spring";
	global.__objectNames[292] = "obj_spring_hidden";
	global.__objectNames[293] = "obj_spring_timed";
	global.__objectNames[294] = "obj_spring_super";
	global.__objectNames[295] = "obj_propellerblock";
	global.__objectNames[296] = "obj_3upmoon";
	global.__objectNames[297] = "obj_acecoin";
	global.__objectNames[298] = "obj_pswitch";
	global.__objectNames[299] = "obj_eswitch";
	global.__objectNames[300] = "obj_eswitch_red";
	global.__objectNames[301] = "obj_pplatform";
	global.__objectNames[302] = "obj_quicksand";
	global.__objectNames[303] = "obj_blowpipe_top";
	global.__objectNames[304] = "obj_blowpipe_bottom";
	global.__objectNames[305] = "obj_blowpipe_left";
	global.__objectNames[306] = "obj_blowpipe_right";
	global.__objectNames[307] = "obj_walltriangle_r";
	global.__objectNames[308] = "obj_walltriangle_ir";
	global.__objectNames[309] = "obj_walltriangle_l";
	global.__objectNames[310] = "obj_walltriangle_il";
	global.__objectNames[311] = "obj_flippers_top";
	global.__objectNames[312] = "obj_flippers_bottom";
	global.__objectNames[313] = "obj_flippers_left";
	global.__objectNames[314] = "obj_flippers_right";
	global.__objectNames[315] = "obj_fallingspike";
	global.__objectNames[316] = "obj_veggie_small";
	global.__objectNames[317] = "obj_veggie_large";
	global.__objectNames[318] = "obj_veggie_coin";
	global.__objectNames[319] = "obj_veggie_multicoin";
	global.__objectNames[320] = "obj_veggie_sprout";
	global.__objectNames[321] = "obj_veggie_bomb";
	global.__objectNames[322] = "obj_veggie_shell";
	global.__objectNames[323] = "obj_powblock";
	global.__objectNames[324] = "obj_mblock";
	global.__objectNames[325] = "obj_pullmush";
	global.__objectNames[326] = "obj_digsand";
	global.__objectNames[327] = "obj_key";
	global.__objectNames[328] = "obj_keyhole";
	global.__objectNames[329] = "obj_warptop";
	global.__objectNames[330] = "obj_warpbottom";
	global.__objectNames[331] = "obj_warpleft";
	global.__objectNames[332] = "obj_warpright";
	global.__objectNames[333] = "obj_door";
	global.__objectNames[334] = "obj_door_locked";
	global.__objectNames[335] = "obj_door_hidden";
	global.__objectNames[336] = "obj_door_hidden_locked";
	global.__objectNames[337] = "obj_door_bomb";
	global.__objectNames[338] = "obj_postchange";
	global.__objectNames[339] = "obj_warproom";
	global.__objectNames[340] = "obj_warpcannon";
	global.__objectNames[341] = "obj_giantwarpcannon";
	global.__objectNames[342] = "obj_physicsparent";
	global.__objectNames[343] = "obj_powerupparent";
	global.__objectNames[344] = "obj_enemyparent";
	global.__objectNames[345] = "obj_deactenemyparent";
	global.__objectNames[346] = "obj_subconenemyparent";
	global.__objectNames[347] = "obj_bossparent";
	global.__objectNames[348] = "obj_blockparent";
	global.__objectNames[349] = "obj_grayblockparent";
	global.__objectNames[350] = "obj_worldparent";
	global.__objectNames[351] = "obj_panelparent";
	global.__objectNames[352] = "obj_pullparent";
	global.__objectNames[353] = "obj_carryparent";
	global.__objectNames[354] = "obj_holdparent";
	global.__objectNames[355] = "obj_slopeparent";
	global.__objectNames[356] = "obj_deactivation";
	global.__objectNames[357] = "obj_deadmario";
	global.__objectNames[358] = "obj_goalmario";
	global.__objectNames[359] = "obj_warpnoteblock";
	global.__objectNames[360] = "obj_doormario";
	global.__objectNames[361] = "obj_puller";
	global.__objectNames[362] = "obj_wallrunner";
	global.__objectNames[363] = "obj_slider";
	global.__objectNames[364] = "obj_spinner";
	global.__objectNames[365] = "obj_statue";
	global.__objectNames[366] = "obj_rockroller";
	global.__objectNames[367] = "obj_karateattack";
	global.__objectNames[368] = "obj_1up";
	global.__objectNames[369] = "obj_poison";
	global.__objectNames[370] = "obj_mushroom";
	global.__objectNames[371] = "obj_fireflower";
	global.__objectNames[372] = "obj_hammersuit";
	global.__objectNames[373] = "obj_leaf";
	global.__objectNames[374] = "obj_tanookisuit";
	global.__objectNames[375] = "obj_frogsuit";
	global.__objectNames[376] = "obj_bombshroom";
	global.__objectNames[377] = "obj_iceflower";
	global.__objectNames[378] = "obj_superflower";
	global.__objectNames[379] = "obj_carrot";
	global.__objectNames[380] = "obj_ninjasuit";
	global.__objectNames[381] = "obj_beeshroom";
	global.__objectNames[382] = "obj_blueshell";
	global.__objectNames[383] = "obj_penguinsuit";
	global.__objectNames[384] = "obj_propellershroom";
	global.__objectNames[385] = "obj_boomerangflower";
	global.__objectNames[386] = "obj_walljumpshroom";
	global.__objectNames[387] = "obj_acorn";
	global.__objectNames[388] = "obj_cloudflower";
	global.__objectNames[389] = "obj_rockshroom";
	global.__objectNames[390] = "obj_pyreflower";
	global.__objectNames[391] = "obj_swoopersuit";
	global.__objectNames[392] = "obj_karatesuit";
	global.__objectNames[393] = "obj_supercrown";
	global.__objectNames[394] = "obj_star";
	global.__objectNames[395] = "obj_hatch";
	global.__objectNames[396] = "obj_yoshi";
	global.__objectNames[397] = "obj_yoshi_runaway";
	global.__objectNames[398] = "obj_yoshi_abandon";
	global.__objectNames[399] = "obj_tongue";
	global.__objectNames[400] = "obj_yoshifire";
	global.__objectNames[401] = "obj_kuriboshoe";
	global.__objectNames[402] = "obj_getshoe";
	global.__objectNames[403] = "obj_powerupsprout";
	global.__objectNames[404] = "obj_reserveitem";
	global.__objectNames[405] = "obj_grasspowerup";
	global.__objectNames[406] = "obj_getpowerup";
	global.__objectNames[407] = "obj_fireball";
	global.__objectNames[408] = "obj_hammer";
	global.__objectNames[409] = "obj_minibomb";
	global.__objectNames[410] = "obj_iceball";
	global.__objectNames[411] = "obj_superball";
	global.__objectNames[412] = "obj_shuriken";
	global.__objectNames[413] = "obj_boomerang_b";
	global.__objectNames[414] = "obj_cloud";
	global.__objectNames[415] = "obj_pyreball";
	global.__objectNames[416] = "obj_invincibility";
	global.__objectNames[417] = "obj_galoomba_hold";
	global.__objectNames[418] = "obj_spikeball";
	global.__objectNames[419] = "obj_wiggler_body";
	global.__objectNames[420] = "obj_plantfire";
	global.__objectNames[421] = "obj_plantball";
	global.__objectNames[422] = "obj_busterpickup";
	global.__objectNames[423] = "obj_blargg_jump";
	global.__objectNames[424] = "obj_torpedoglove";
	global.__objectNames[425] = "obj_torpedoted";
	global.__objectNames[426] = "obj_lavalotusball";
	global.__objectNames[427] = "obj_monty";
	global.__objectNames[428] = "obj_montyjump";
	global.__objectNames[429] = "obj_lakitu_egg";
	global.__objectNames[430] = "obj_lakituticker";
	global.__objectNames[431] = "obj_lotusball";
	global.__objectNames[432] = "obj_dinoflames";
	global.__objectNames[433] = "obj_firesnake_part";
	global.__objectNames[434] = "obj_angrysun_movement";
	global.__objectNames[435] = "obj_boocircle_boo";
	global.__objectNames[436] = "obj_boosnake_trail";
	global.__objectNames[437] = "obj_crumblebones";
	global.__objectNames[438] = "obj_rotodisc_path";
	global.__objectNames[439] = "obj_firebarball";
	global.__objectNames[440] = "obj_chains";
	global.__objectNames[441] = "obj_magikoopa2";
	global.__objectNames[442] = "obj_magic";
	global.__objectNames[443] = "obj_bowserstatue_fire";
	global.__objectNames[444] = "obj_mechakoopa_hold";
	global.__objectNames[445] = "obj_bobomb_hold";
	global.__objectNames[446] = "obj_cannonbomb";
	global.__objectNames[447] = "obj_bullet";
	global.__objectNames[448] = "obj_bullet_side";
	global.__objectNames[449] = "obj_bullet_homing";
	global.__objectNames[450] = "obj_cannonball";
	global.__objectNames[451] = "obj_largeball";
	global.__objectNames[452] = "obj_engines";
	global.__objectNames[453] = "obj_engines2";
	global.__objectNames[454] = "obj_vengines";
	global.__objectNames[455] = "obj_vengines2";
	global.__objectNames[456] = "obj_wrench";
	global.__objectNames[457] = "obj_snifitball";
	global.__objectNames[458] = "obj_bombguyup";
	global.__objectNames[459] = "obj_panserfire";
	global.__objectNames[460] = "obj_magiccircle";
	global.__objectNames[461] = "obj_magicring";
	global.__objectNames[462] = "obj_magicball";
	global.__objectNames[463] = "obj_lemmyball";
	global.__objectNames[464] = "obj_birdo_egg";
	global.__objectNames[465] = "obj_mouser_bomb";
	global.__objectNames[466] = "obj_mouser_thrownbomb";
	global.__objectNames[467] = "obj_reznor_platform";
	global.__objectNames[468] = "obj_reznor_enemy";
	global.__objectNames[469] = "obj_reznor_fire";
	global.__objectNames[470] = "obj_bowserfire";
	global.__objectNames[471] = "obj_enemy_dead";
	global.__objectNames[472] = "obj_enemy_multidead";
	global.__objectNames[473] = "obj_enemy_stomped";
	global.__objectNames[474] = "obj_enemy_frozen";
	global.__objectNames[475] = "obj_frozenenemy_pickup";
	global.__objectNames[476] = "obj_vegenemy";
	global.__objectNames[477] = "obj_stomped";
	global.__objectNames[478] = "obj_shell";
	global.__objectNames[479] = "obj_shell_held";
	global.__objectNames[480] = "obj_brohammer";
	global.__objectNames[481] = "obj_brofire";
	global.__objectNames[482] = "obj_boomerang";
	global.__objectNames[483] = "obj_lightning";
	global.__objectNames[484] = "obj_sumoflame";
	global.__objectNames[485] = "obj_firechomp_tail";
	global.__objectNames[486] = "obj_flyingbro_rider";
	global.__objectNames[487] = "obj_generatorcheep";
	global.__objectNames[488] = "obj_blockcoin";
	global.__objectNames[489] = "obj_beanstalk";
	global.__objectNames[490] = "obj_vinewarp";
	global.__objectNames[491] = "obj_coinchain";
	global.__objectNames[492] = "obj_thrownbrick";
	global.__objectNames[493] = "obj_shard";
	global.__objectNames[494] = "obj_arrowplatform_move";
	global.__objectNames[495] = "obj_blocktrain_front";
	global.__objectNames[496] = "obj_blocktrain_middle";
	global.__objectNames[497] = "obj_blocktrain_back";
	global.__objectNames[498] = "obj_blocktrain_killer";
	global.__objectNames[499] = "obj_expandplatblock";
	global.__objectNames[500] = "obj_movingrope_rope";
	global.__objectNames[501] = "obj_vegetable_small";
	global.__objectNames[502] = "obj_vegetable_large";
	global.__objectNames[503] = "obj_veggiecoin";
	global.__objectNames[504] = "obj_multiveggiecoin";
	global.__objectNames[505] = "obj_grassbomb";
	global.__objectNames[506] = "obj_smb2shellup";
	global.__objectNames[507] = "obj_pow";
	global.__objectNames[508] = "obj_powkiller";
	global.__objectNames[509] = "obj_mblockup";
	global.__objectNames[510] = "obj_coinchange";
	global.__objectNames[511] = "obj_spring_blue";
	global.__objectNames[512] = "obj_blownbubble";
	global.__objectNames[513] = "obj_score";
	global.__objectNames[514] = "obj_smoke";
	global.__objectNames[515] = "obj_statuesmoke";
	global.__objectNames[516] = "obj_spinsmoke";
	global.__objectNames[517] = "obj_spinthump";
	global.__objectNames[518] = "obj_bubble";
	global.__objectNames[519] = "obj_sparkletrail";
	global.__objectNames[520] = "obj_rain";
	global.__objectNames[521] = "obj_mapcard";
	global.__objectNames[522] = "obj_explosion";
	global.__objectNames[523] = "obj_flag";
	global.__objectNames[524] = "obj_lightningsheet";
	global.__objectNames[525] = "obj_messagebox";
	global.__objectNames[526] = "obj_pausemenu";
	global.__objectNames[527] = "obj_savemenu";
	global.__objectNames[528] = "obj_inventoryprev";
	global.__objectNames[529] = "obj_blockbumper";
	global.__objectNames[530] = "obj_stomp";
	global.__objectNames[531] = "obj_persistent";
	global.__objectNames[532] = "obj_titlescreen";
	global.__objectNames[533] = "obj_mushtoad";
	global.__objectNames[534] = "obj_chest";
	global.__objectNames[535] = "obj_gameover";
	global.__objectNames[536] = "obj_mariostart";
	global.__objectNames[537] = "obj_roulettemanager";
	global.__objectNames[538] = "obj_cardmanager";
	global.__objectNames[539] = "obj_card";
	global.__objectNames[540] = "obj_switch";
	global.__objectNames[541] = "obj_hammerprize";
	global.__objectNames[542] = "obj_mappipemanager";
	global.__objectNames[543] = "obj_warpmapscreen";
	global.__objectNames[544] = "obj_up";
	global.__objectNames[545] = "obj_down";
	global.__objectNames[546] = "obj_left";
	global.__objectNames[547] = "obj_right";
	global.__objectNames[548] = "obj_endmarker";
	global.__objectNames[549] = "obj_speedmarker";
	global.__objectNames[550] = "obj_clockwise";
	global.__objectNames[551] = "obj_cclockwise";
	global.__objectNames[552] = "obj_clockwiseb";
	global.__objectNames[553] = "obj_cclockwiseb";


	// create another array that has the correct entries
	var len = array_length(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
